apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developerbinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developerrole
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: developer-group
